version: "3.8"

services:
  app:
    build:
      context: ./docker/php
    container_name: job-crm-app
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    ports:
      - "9000:9000"
    depends_on:
      - mysql

  nginx:
    image: nginx:1.25
    container_name: job-crm-nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: job-crm-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: job_crm
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql

  node:
    image: node:20
    container_name: job-crm-node
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    tty: true

volumes:
  mysql-data: